
import "./globals.css";
import "todomvc-app-css/index.css";
import "todomvc-common/base.css";
import "@/app/todo/app.css";
import {App} from "@/app/todo/app";


export const metadata = {
  title: "TodoMVC: Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" data-framework="react">
      <head>
          <meta charSet="UTF-8"/>
          <meta name="description" content="A TodoMVC written in React."/>
          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
          <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
          <title>TodoMVC: React</title>
          <link rel="icon" href="/favicon.ico"/>
      </head>
      <body>
      <section className="todoapp" id="root"><App>{children}</App></section>
      <footer className="info">
          <p>Double-click to edit a todo</p>
          <p>Created by the TodoMVC Team</p>
          <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
      </footer>
      <script src="./base.js"></script>
      </body>
      </html>
)
    ;
}
